#+LATEX_CLASS: article
#+LANGUAGE: es
#+LATEX_HEADER: \usepackage[AUTO]{babel}
#+LATEX_HEADER: \usepackage{fancyvrb}
#+OPTIONS: toc:nil
#+DATE:
#+AUTHOR: Dr. Miguel Carrillo Barajas \\
#+AUTHOR: Sara Doris Montes Incin \\
#+AUTHOR: Mauricio Esquivel Reyes \\
#+TITLE: Sesión de laboratorio 09 \\
#+TITLE: Lógica Computacional

* Formulas de Horn
La sintaxis de las formulas (proposicionales) de Horn, HORN, se define con notación BNF como sigue.

\[HORN                ::= <ClausulaDeHorn> | <ClausulaDeHorn> \land HORN.\]
\[<ClausulaDeHorn>    ::= (<Premisa> \rightarrow <Conclusion>)\]
\[<Premisa>           ::= <Atom> | (<Atom> \land <Premisa>)\]
\[<Conclusion>        ::= <Atom>\]
\[<Atom>              ::= \bot | \top | <Variable>\]
\[<Variable>          ::= v <Indice>\]
\[<Indice>            ::= i, i \in \mathbb{N}.\]

Una formula de Horn es una conjunción de clausulas de Horn.
Una cláusula de Horn es una implicación cuya premisa es una conjuncion de 
átomos (\bot,\top,v_i) y cuya conclusión es un átomo.

#+begin_src haskell
-- Atomos para clausulas de Horn
data Hatom  =  Htop | Hbot | Hvar Indice deriving (Eq) 
-- Clausula de Horn: Premisa=[atomo1,...,atomoN] -> Conclusion=Atomo
data Fhorn  =   Himp [Hatom] Hatom                     
 -- Conjuncion de formulas de Horn 
              | Hand Fhorn Fhorn  deriving (Eq, Show)  
#+end_src
** Átomos marcados
Nos regresa True si todos los átomos de una premisa estan marcados. False en otro caso
#+begin_src haskell
atomosMarcados :: [Hatom] -> [Hatom] -> Bool
atomosMarcados lm premisa = and [a `elem` lm | a <- premisa] 
#+end_src
** Marca conclusiones 
Agregá las conclusiones de una lista de cláusulas de Horn a una lista de átomos marcados.
#+begin_src haskell
marcaConclusiones :: [Hatom] -> [Fhorn] -> [Hatom]
marcaConclusiones lMarcados lcH = case lcH of
 [] -> lMarcados
 (Himp _ c):cHs -> marcaConclusiones (c:lMarcados) cHs
 _  -> error $ "marcaConclusiones: no es una clausula de Horn: "++show (head lcH)
#+end_src
** Cláusulas marcables 
Regresa la lista de clausulas de $\phi$ que tienen una conclusión marcable.
Def. $f$ es una cláusula con conclusión marcable si: $f = p \rightarrow c$, los atomos de $p$ están marcados, y $c$ no está marcada.
#+begin_src haskell
clausulasHmarcables :: [Hatom] -> Fhorn -> [Fhorn]
clausulasHmarcables lMarcados phi = case phi of
 Himp premisa conclusion -> if (atomosMarcados lMarcados premisa) && 
(conclusion `notElem` lMarcados)
  then [phi]
  else []
 Hand f1 f2 -> clausulasHmarcables lMarcados f1 ++ clausulasHmarcables lMarcados f2
#+end_src
** Marca formula de Horn
Mientras $\phi$ tenga una clausula con conclusion marcable, marca las conclusiones de dichas clausulas.
Def. $f$ es una clausula con conclusión marcable si: $f = p \rightarrow c$, los atomos de $p$ están marcados, y $c$ no está marcada.
#+begin_src haskell
marcaFormulaHorn :: [Hatom] -> Fhorn -> [Hatom]
marcaFormulaHorn lMarcados phi = 
    if cHornMarcables == []
        then lMarcados
        else marcaFormulaHorn lMarcadosNew phi
    where
    cHornMarcables  = clausulasHmarcables lMarcados phi
    lMarcadosNew    = marcaConclusiones lMarcados cHornMarcables
#+end_src
** Horn es satisfacible
#+begin_src haskell
enSatHorn :: Fhorn -> Bool
enSatHorn phi = if Hbot `elem` (marcaFormulaHorn [Htop] phi)
                    then False
                    else True
#+end_src

* Práctica Urgente 2
** Es cláusula
Función que nos indica si una fórmula es una cláusula.
#+begin_src haskell
esClausula :: PL -> Bool
#+end_src
** Es CNF
Función que nos indica si una fórmula esta en forma normal conjuntiva.
#+begin_src haskell
esCNF :: PL -> Bool
#+end_src
** Es término
Función que nos indica si una fórmula es un término.
#+begin_src haskell
esTermino :: PL -> Bool
#+end_src
** Es DNF
Función que nos indica si una fórmula esta en forma normal disyuntiva.
#+begin_src haskell
esDNF :: PL -> Bool
#+end_src
